<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="YKToolkit.Controls">
      <HintPath>..\..\..\YKToolkit\YKToolkit.Controls.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\**\*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="itext" Version="9.5.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.5.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3719.77" />
  </ItemGroup>
</Project>
